#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PTE_APP.Resource", IsApplication=true)]

namespace PTE_APP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int scale_bounce_from_center = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int scale_bounce_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Slide_in_from_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Slide_in_from_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Slide_out_to_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Slide_out_to_right = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int option_correct = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int option_incorrect = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int option_nomal = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int author = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int books = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int header = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int listening = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int listening_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int next = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int paper = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pause = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int play = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int practice = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int previous = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int reading = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int reading_on = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int script = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shadow_layout = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int speaking = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int speaking_on = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int stop = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int text_background_hide = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int writting = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int writting_on = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int imageButton_lt_logo = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int imageButton_lt_nextquiz = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int imageButton_lt_play = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int imageButton_lt_previousquiz = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int imageButton_lt_stop = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int imageButton_lt_viewscript = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int imageButton_main_listening = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int imageButton_main_reading = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int imageButton_main_speaking = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int imageButton_main_writting = 2131165209;
			
			// aapt resource value: 0x7f07002d
			public const int imageButton_tm_logo = 2131165229;
			
			// aapt resource value: 0x7f070021
			public const int imageView1 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int imageView2 = 2131165219;
			
			// aapt resource value: 0x7f07002b
			public const int imageView_adv = 2131165227;
			
			// aapt resource value: 0x7f070016
			public const int imageView_main_middle = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int imageView_main_upside = 2131165205;
			
			// aapt resource value: 0x7f070026
			public const int imageView_testmain_logo = 2131165222;
			
			// aapt resource value: 0x7f07001e
			public const int imageView_ti_logo = 2131165214;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout1 = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070029
			public const int linearLayout3 = 2131165225;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout_lt2 = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout_lt_conntent = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout_lt_main = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout_lt_menu = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout_lt_player = 2131165190;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout_main_funcion = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int linearLayout_st_top = 2131165212;
			
			// aapt resource value: 0x7f07002a
			public const int linearLayout_testitems_bottom = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int linearLayout_testitems_function = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int linearLayout_testitems_top = 2131165221;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout_tm_divider = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int linearLayout_tm_info = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout_tm_main = 2131165213;
			
			// aapt resource value: 0x7f070030
			public const int linearLayout_tm_testlist = 2131165232;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout_tm_top = 2131165228;
			
			// aapt resource value: 0x7f070009
			public const int progressBar_lt_progress = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int scrollView_lt_content = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int scrollView_lt_script = 2131165195;
			
			// aapt resource value: 0x7f07002f
			public const int scrollView_tm_testlist = 2131165231;
			
			// aapt resource value: 0x7f070027
			public const int textView1 = 2131165223;
			
			// aapt resource value: 0x7f07000a
			public const int textView_lt_progress = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int textView_lt_question = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int textView_lt_script = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int textView_lt_tip = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int textView_lt_title = 2131165187;
			
			// aapt resource value: 0x7f070024
			public const int textView_ti_tauthor = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int textView_ti_tname = 2131165218;
			
			// aapt resource value: 0x7f07002e
			public const int textView_tm_title = 2131165230;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListeningTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SpeakingTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TestItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TestItemType = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TestMain = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060011
			public const int App_RootDir = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int App_TestDir = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int App_TestListening = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int App_TestReading = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int App_TestSpeaking = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int App_TestWritting = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int Diction_Tip = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int GapFill_Tip = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MultipleChoice1_Tip = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MultipleChoice2_Tip = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Summary_Tip = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int TestOption_Describe_Image = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int TestOption_Dictation = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int TestOption_Gap_Fill = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int TestOption_Highlight_Incorrect_Words = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int TestOption_Multiple_Choice1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int TestOption_Multiple_Choice2 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int TestOption_Read_Aloud = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int TestOption_Repeat_Sentence = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int TestOption_Retell_Lecture = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int TestOption_Summary = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int Warining_EndofTest = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int Warining_FistofTest = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int Warining_LoadFail = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int Warining_SDFail = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int Warining_TestNotExist = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
